export const NOOP = 'NOOP';

export const LOGIN = 'LOGIN';
export const AUTHORIZE = 'AUTHORIZE';

export const SEARCH_BOOKS_REQUEST = 'SEARCH_BOOKS_REQUEST';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAILURE = 'SEARCH_BOOKS_FAILURE';
export const SEARCH_BOOKS_CANCEL = 'SEARCH_BOOKS_CANCEL';

export const TAKE_BOOK = 'TAKE_BOOK';
export const ROLLBACK_TAKE_BOOK = 'ROLLBACK_TAKE_BOOK';
export const RETURN_BOOK = 'RETURN_BOOK';
export const ROLLBACK_RETURN_BOOK = 'ROLLBACK_RETURN_BOOK';

export const TRACK_BOOK = 'TRACK_BOOK';
export const ROLLBACK_TRACK_BOOK = 'ROLLBACK_TRACK_BOOK';
export const UNTRACK_BOOK = 'UNTRACK_BOOK';
export const ROLLBACK_UNTRACK_BOOK = 'ROLLBACK_UNTRACK_BOOK';

export const LIKE_BOOK = 'LIKE_BOOK';
export const ROLLBACK_LIKE_BOOK = 'ROLLBACK_LIKE_BOOK';
export const DISLIKE_BOOK = 'DISLIKE_BOOK';
export const ROLLBACK_DISLIKE_BOOK = 'ROLLBACK_DISLIKE_BOOK';

export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_SEARCH_BY = 'UPDATE_SEARCH_BY';
export const UPDATE_SEARCH_SORT_BY = 'UPDATE_SEARCH_SORT_BY';
export const UPDATE_SEARCH_FILTER_BY = 'UPDATE_SEARCH_FILTER_BY';
export const UPDATE_SEARCH_DISPLAY_MODE = 'UPDATE_SEARCH_DISPLAY_MODE';
