export const NOOP = 'NOOP';

export const LOGIN = 'LOGIN';
export const AUTHORIZE = 'AUTHORIZE';

export const SEARCH_BOOKS_REQUEST = 'SEARCH_BOOKS_REQUEST';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAILURE = 'SEARCH_BOOKS_FAILURE';
export const SEARCH_BOOKS_CANCEL = 'SEARCH_BOOKS_CANCEL';

export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_SEARCH_BY = 'UPDATE_SEARCH_BY';
export const UPDATE_SEARCH_SORT_BY = 'UPDATE_SEARCH_SORT_BY';
export const UPDATE_SEARCH_FILTER_BY = 'UPDATE_SEARCH_FILTER_BY';
export const UPDATE_SEARCH_DISPLAY_MODE = 'UPDATE_SEARCH_DISPLAY_MODE';
